server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: chat-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:vinaacademy_chat}
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        use_sql_comments: true
        order_inserts: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
logging:
  level:
    root: INFO
    vn:
      vinaacademy:
        security: TRACE
        chat: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG


management:
  endpoints:
    web:
      base-path: /actuator
  server:
    port: '8081'


security:
  oauth2:
    provider:
      token-uri: ${SECURITY_OAUTH2_TOKEN_URI:http://localhost:8080/oauth2/token}
    grpc-client:
      scopes: ${SECURITY_OAUTH2_SCOPE_1:api.read}, ${SECURITY_OAUTH2_SCOPE_2:api.write}
      client-id: ${SECURITY_OAUTH2_GRPC_CLIENT_ID:grpc-client}
      client-secret: ${SECURITY_OAUTH2_GRPC_CLIENT_SECRET:grpc-secret}
  grpc:
    grpc-address: ${SECURITY_JWT_GRPC_ADDRESS:localhost:9090}
    enable-keep-alive: ${SECURITY_JWT_ENABLE_KEEP_ALIVE:true}
    keep-alive-time: ${SECURITY_JWT_KEEP_ALIVE_TIME:30}
    keep-alive-timeout: ${SECURITY_JWT_KEEP_ALIVE_TIMEOUT:5}
