server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: chat-service
  grpc:
    server:
      enabled: false
    client:
      channels:
        platform-server:
          address: ${PLATFORM_GRPC_URL:localhost:9090}
          enable-keep-alive: true
          keep-alive-time: 30s
          keep-alive-timeout: 5s
          max-inbound-message-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:vinaacademy_chat}
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        use_sql_comments: true
        order_inserts: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          grpc-client:
            provider: as-vina
            client-id: ${GRPC_CLIENT_ID:grpc-client}
            client-secret: ${GRPC_CLIENT_SECRET:grpc-secret}
            authorization-grant-type: client_credentials
            scope:
              - "api.read"
              - "api.write"
        provider:
          as-vina:
            token-uri: ${AS_VINA_TOKEN_URI:http://localhost:8080/oauth2/token}
springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
logging:
  level:
    root: INFO
    vn:
      vinaacademy:
        chat: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG